news/urls.py
from django.urls import path, re_path

from .views import NewsList, NewsRubric, NewsDetail, NewsStories, CountryNewsListView

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='list'),
    re_path(r'^news-(?P<slug>.*)/$', CountryNewsListView.as_view(),name='news-by-country'),
    path('<int:pk>/', NewsDetail.as_view(), name='detail'),
    path('<slug:slug>/', NewsRubric.as_view(), name='rubric'),
    path('stories/<slug:slug>/', NewsStories.as_view(), name='stories'),
]

partners/urls.py
from django.urls import path
from django.views.generic import TemplateView

from partners.views import PartnerPageDetailView

urlpatterns = [
    path('<slug:slug>/', PartnerPageDetailView.as_view(), name='partners-online'),

]

pomogator/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.static import serve

from core.views import SearchResultsView, FeedbackView
from filebrowser.sites import site as filebrowser_site
from news.views import IndexPage
from pomogator import settings
from pomogator.feeds import show_feed
from pomogator.sitemap import StaticSitemap, DinamicNewsSitemap, DinamicArticleSitemap, DinamicPageSitemap, \
    DinamicRubricSitemap, DinamicCountrySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticSitemap,
    'rubrics': DinamicRubricSitemap,
    'news': DinamicNewsSitemap,
    'article': DinamicArticleSitemap,
    'page': DinamicPageSitemap,
    'country': DinamicCountrySitemap,
}

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', filebrowser_site.urls),
    path('trumbowyg/', include('trumbowyg.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('news/', include('news.urls', namespace='news')),
    path('articles/', include('news.article.urls', namespace="articles")),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    # partners
    re_path(r'^', include('partners.urls')),
    #
    re_path(r'^robots\.txt', include('robots.urls')),
    # re_path(r'^sitemap.xml$', cache_page(60)(sitemap), {'sitemaps': [sitemaps]}, name='cached-sitemap'),
    re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='cached-sitemap'),
    re_path(r'^feed/(?P<feed_name>.*)\.xml$', show_feed),
    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    re_path(r'^(?P<url>.*/)$', views.flatpage),

]

partners/models.py
from django.db import models
from tinymce import HTMLField

from news.models import Stories


class SEOFieldsMixin(models.Model):
    """ SEO абстрактная модель"""
    meta_title = models.CharField(u'Meta Title', max_length=255, blank=True)
    meta_description = models.TextField(u'Meta Description', blank=True)
    meta_keywords = models.TextField(u'Meta Keywords', blank=True)

    class Meta:
        abstract = True


class PartnerPage(SEOFieldsMixin):
    """
    Страницы партнеров с виджетами
    """

    title = models.CharField('Название', max_length=255)
    subtitle = models.CharField(verbose_name='Подзаголовок', max_length=200, blank=True, null=True)
    disc = HTMLField('HTML-Описание', max_length=5000, blank=True)
    slug = models.CharField('Slug', max_length=255, unique=True, help_text="Например tours-online, avia-online и тп")
    news_subjects = models.ManyToManyField(Stories, blank=True, verbose_name=u'Сюжеты', related_name='news_subjects')

    class Meta:
        verbose_name = 'Страница партнеров с виджетами'
        verbose_name_plural = 'Страницы партнеров с виджетами'

    def __str__(self):
        return self.title


class PartnerWidgetScript(models.Model):
    """
    Скрипты виджетов по а/б, турам и отелям
    """
    region = models.ForeignKey(PartnerPage,  on_delete=models.CASCADE)
    name = models.CharField('Название', max_length=255,  default='', blank=False, null=False)
    content = models.TextField('HTML-код скрипта', max_length=5000, blank=True)
    order = models.PositiveSmallIntegerField("Сортировка", default=0, blank=False, null=False)

    class Meta:
        ordering = ['order']
        verbose_name = "Скрипт виджета"
        verbose_name_plural = "Скрипты виджета"

    def __str__(self):
        return self.name

partners/views.py
from django.views.generic import DetailView

from partners.models import PartnerPage


class PartnerPageDetailView(DetailView):
    model = PartnerPage
    template_name = 'partners/detail.html'

partners/templates/partners/detail.html
{% extends "base.html" %}{% load news %}

{% block title %}{% if object.meta_title %}{{ object.meta_title }}{% else %}{{ object.title }}{% endif %}{% endblock %}
{% block meta_name %}
  <meta name="keywords" content="{% if not object.meta_keywords %}{{ object.title }}{% else %}{{ object.meta_keywords }}{% endif %}">
  <meta name="description" content="{% if not object.meta_description %}{{ object.title }}{% else %}{{ object.meta_description }}{% endif %}">
{% endblock %}
{% block javascript %}
{% endblock %}
{% block top_branding %}{% endblock %}
{% block headershow_banner_place %}{% endblock %}
{% block breadcrumbs %}
  <a href="/">Главная</a>
  <span>{{ object.title }}</span>
{% endblock %}
{% block main %}
  <div class="grid grid--bleed">
    <div class="grid__col-12">
      <div class="panel">
        <div class="panel-heading">
          <h1>{{ object.title }}</h1>
        </div>

        <div class="panel-body">
          <div class="panel-body-wrap--padding text">
            {{ object.disc|safe }}
          </div>
          <div class="panel-body-wrap--padding text pt-0">
            {% for foo in object.partnerwidgetscript_set.all %}
              {{ foo.content|safe }}
            {% endfor %}
          </div>
          <div class="grid grid--bleed grid--no-flex-grow">
            {% for subject in object.news_subjects.all|slice:2 %}
            <div class="grid__col-sm-6">
              {% top_news_subject subject count=5 %}
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock main %}