news/article/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    ArticleDetailView,
    RubricArticleListView,
)

app_name = 'articles'

urlpatterns = [
    # '',
    url(r'^$', ArticleListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), name="detail"),
    url(r'^(?P<rubric_name>.*)/$', RubricArticleListView.as_view(), name='article_by_rubric'),
]

news/urls.py
from django.urls import path, re_path

from .views import NewsList, NewsRubric, NewsDetail, NewsStories, CountryNewsListView

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='list'),
    re_path(r'^news-(?P<slug>.*)/$', CountryNewsListView.as_view(),name='news-by-country'),
    path('<int:pk>/', NewsDetail.as_view(), name='detail'),
    path('<slug:slug>/', NewsRubric.as_view(), name='rubric'),
    path('stories/<slug:slug>/', NewsStories.as_view(), name='stories'),
]

pomogator/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.static import serve

from core.views import SearchResultsView, FeedbackView
from filebrowser.sites import site as filebrowser_site
from news.views import IndexPage
from pomogator import settings
from pomogator.feeds import show_feed
from pomogator.sitemap import StaticSitemap, DinamicNewsSitemap, DinamicArticleSitemap, DinamicPageSitemap, \
    DinamicRubricSitemap, DinamicCountrySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticSitemap,
    'rubrics': DinamicRubricSitemap,
    'news': DinamicNewsSitemap,
    'article': DinamicArticleSitemap,
    'page': DinamicPageSitemap,
    'country': DinamicCountrySitemap,
}

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', filebrowser_site.urls),
    path('trumbowyg/', include('trumbowyg.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('news/', include('news.urls', namespace='news')),
    path('articles/', include('news.article.urls', namespace="articles")),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    # partners
    re_path(r'^', include('partners.urls')),
    #
    re_path(r'^robots\.txt', include('robots.urls')),
    # re_path(r'^sitemap.xml$', cache_page(60)(sitemap), {'sitemaps': [sitemaps]}, name='cached-sitemap'),
    re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='cached-sitemap'),
    re_path(r'^feed/(?P<feed_name>.*)\.xml$', show_feed),
    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    re_path(r'^(?P<url>.*/)$', views.flatpage),

]

news/article/views.py
import logging

# from django.http import Http404
from django.core.cache import cache
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView

from core.mixins import VisitViewMixin
from ..models import Article, Rubric
from countries.models import Country

log = logging.getLogger(__name__)


class ArticleListView(ListView):
    paginate_by = 20
    template_name = "articles/article_list.html"
    model = Article
    current_country = None
    current_tourismtype = None

    def get(self, request, *args, **kwargs):
        return super(ArticleListView, self).get(request, *args, **kwargs)

    def get_queryset(self, **kwargs):
        # print(self.request.GET.get('tourismtype'))

        qs = self.model.objects.filter(
            published=True, pubdate__lte=timezone.now())

        if 'country' in self.request.GET:
            country_slug = self.request.GET.get('country')
            self.current_country = get_object_or_404(
                Country, slug=country_slug)
            qs = qs.filter(countries=self.current_country)

        return qs

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['h1'] = "Журнал: статьи по туризму"
        context['show_map'] = True
        context['current_country'] = self.current_country
        context['current_tourismtype'] = self.current_tourismtype
        return context


class ArticleDetailView(VisitViewMixin, DetailView):
    template_name = "articles/article_detail.html"
    model = Article
    queryset = Article.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        same_articles = Article.objects.filter(
            published=True
        ).exclude(id=self.object.id).order_by("-created")

        if same_articles.count():
            context['same_articles'] = same_articles[0]

        return context


class RubricArticleListView(ListView):
    paginate_by = 20
    model = Article
    template_name = "articles/article_list.html"
    rubric = None
    current_country = None
    current_tourismtype = None

    def get(self, request, *args, **kwargs):
        self.rubric = get_object_or_404(Rubric, title_en=kwargs['rubric_name'])
        return super(RubricArticleListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(published=True, rubrics=self.rubric)

    def get_context_data(self, **kwargs):
        context = super(RubricArticleListView, self).get_context_data(**kwargs)
        context['h1'] = self.rubric.title
        context['show_map'] = False
        context['current_country'] = self.current_country
        context['rubric'] = self.rubric
        return context

news/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from core.mixins import VisitViewMixin
from countries.models import Country
from news.models import News, Rubric, Stories


class IndexPage(TemplateView):
    template_name = 'index.html'


class NewsList(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list.html'

    def get_queryset(self):
        qs = self.model.objects.filter(published=True)
        return qs


class NewsRubric(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list.html'
    rubric = None

    def get_queryset(self):
        rubric = get_object_or_404(Rubric, slug=self.kwargs.get('slug', None))
        # rubric = Rubric.objects.get(slug=self.kwargs.get('slug', None))
        self.rubric = rubric
        qs = self.model.objects.filter(published=True)
        qs = qs.filter(rubrics=rubric)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewsRubric, self).get_context_data(**kwargs)
        context['rubric'] = self.rubric
        return context


class NewsStories(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list_stories.html'
    rubric = None

    def get_queryset(self):
        rubric = get_object_or_404(Stories, slug=self.kwargs.get('slug', None))
        # rubric = Rubric.objects.get(slug=self.kwargs.get('slug', None))
        self.rubric = rubric
        qs = self.model.objects.filter(published=True)
        qs = qs.filter(stories=rubric)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewsStories, self).get_context_data(**kwargs)
        context['rubric'] = self.rubric
        return context


class NewsDetail(VisitViewMixin, DetailView):
    model = News
    template_name = 'news/detail.html'
    queryset = News.objects.all_objects().filter(Q(published=True) | Q(delayed_publication=True))


class CountryNewsListView(ListView):
    paginate_by = 20
    template_name = "news/list_country.html"

    def get_queryset(self, **kwargs):
        return News.objects.filter(
            published=True,
            countries__slug=self.kwargs.get('slug')
        )

    def get_context_data(self, **kwargs):
        context = super(CountryNewsListView, self).get_context_data(**kwargs)
        context['country'] = get_object_or_404(
            Country,
            slug=self.kwargs.get('slug')
        )
        return context

news/templates/news/blocks/_article_top_item.html
{% load thumbnail tags_utils %}
<section class="news-block">
    <div class="news-block__header">
    {% block header %}
        <div class="photo-wrap">
            <a href="{{ object.get_absolute_url }}">{% thumbnail object.get_cover "480x140" crop="center" as image %}
                    <img src="{{ image.url }}" alt="">
                {% empty %}
                    {% thumbnail NOIMAGE_URL "480x140" crop="center" as noimage %}
                    <img src="{{ noimage.url }}" class="noimage" alt="">
                    {% endthumbnail %}
                {% endthumbnail %}</a>

            <span class="photo__title">
                <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
            </span>
        </div>
    {% endblock %}
    </div>

    <div class="news-block__body">
    {% block body %}
        <div class="news-block__text">
            <a class="link-more" href="{{ object.get_absolute_url }}">
            {{ object.text|striptags|strip_blank_paragraphs|truncatechars:350 }}
            </a>
        </div>
    {% endblock %}
    </div>
</section>

news/templates/news/blocks/_forloop_ad_video.html
{% if forloop.counter0 == 0 %}{% load banner_tags %}
  {% get_widget_scripts section=5 %}
{% elif forloop.counter0 == 4 %}
  {% get_widget_scripts section=6 %}
{% elif forloop.counter0 == 9 %}
  {% get_widget_scripts section=7 %}
{% endif %}

news/templates/news/blocks/_forloop_yandex_widget.html
{% if forloop.counter == 6 %}
{#  <div class="pt-10">#}
{#  <h3>Читайте самые интересные материалы:</h3>#}
{#  <script type="text/javascript" src="https://code.giraff.io/data/widget-tourpromru.js" async></script>#}
{#<div id="grf_tourpromru_2" class="pt-15"></div>#}
{#  </div>#}

{#  <script async src="https://yastatic.net/pcode-native/loaders/loader.js"></script>#}
{#  <script>#}
{#    (yaads = window.yaads || []).push({#}
{#      id: "114210-20",#}
{#      render: "#id-114210-20"#}
{#    });#}
{#  </script>#}
{#  <div id="id-114210-20"></div>#}
{% elif forloop.counter == 11 %}
{#  <script async src="https://yastatic.net/pcode-native/loaders/loader.js"></script>#}
{#  <script>#}
{#    (yaads = window.yaads || []).push({#}
{#      id: "114210-23",#}
{#      render: "#id-114210-23"#}
{#    });#}
{#  </script>#}
{#  <div id="id-114210-23"></div>#}
{% endif %}

news/templates/news/blocks/_news_item.html
{% load thumbnail tags_utils %}
<section class="news-block">
    <div class="news-block__header">
    {% block header %}
        <div class="photo-wrap">
            <a href="{{ object.get_absolute_url }}">{% thumbnail object.get_cover.image "480x240" crop="center" as image %}
                    <img src="{{ image.url }}" alt="">
                {% empty %}
                    {% thumbnail NOIMAGE_URL "475x360" crop="center" as noimage %}
                    <img src="{{ noimage.url }}" class="noimage" alt="">
                    {% endthumbnail %}
                {% endthumbnail %}</a>

            <span class="photo__title photo__title--right">
                {% ifnotequal object.get_comment_count 0 %}
                <a class="counter-icon news-block__comments" href="{{ object.get_absolute_url }}#comments"
                    title="Количество комментариев">
                    <span class="fa fa-comment"></span> {{ object.get_comment_count }}
                </a>
                {% endifnotequal %}

                {% if object.video or object.youtube_video %}
                <a class="counter-icon news-block__has-video" href="{{ object.video.get_absolute_url }}"
                    title="Видео">
                    <span class="fa fa-video-camera"></span>
                </a>
                {% endif %}

                {% if object.photogallery %}
                <a class="counter-icon news-block__has-photogallery" href="{{ object.photogallery.get_absolute_url }}"
                    title="Фотографии">
                    <span class="fa fa-camera"></span>
                </a>
                {% endif %}

                <span title="Количество просмотров" class="counter-icon visits_count noselect">
                    <span class="fa fa-eye"></span> {{ object.get_visits }}
                </span>
            </span>
        </div>
    {% endblock %}
    </div>

    <div class="news-block__body">
    {% block body %}
        <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
        <div class="news-block__text">
            <a class="link-more" href="{{ object.get_absolute_url }}">
            {{ object.text|striptags|strip_blank_paragraphs|truncatechars:350 }}
            </a>
        </div>
    {% endblock %}
    </div>

    <div class="news-block__footer">
    {% block footer %}
        {% ifnotequal object.countries.count 0 %}
        {% with object.countries.all as labels %}
            {% include "includies/blocks/labels.html" %}
        {% endwith %}
        {% endifnotequal %}

        <div class="no-labels">
            <span class="news-block__date date">
                <span class="fa fa-clock-o"></span> {{ object.pubdate|date:"d M y" }}
            </span>
        </div>
    {% endblock %}
    </div>
</section>

news/templates/news/blocks/_top_articles.html
{% if object_list|length %}{% load banner_tags static %}
{#<link rel="stylesheet" href="{% static 'css/ui/articles.css' %}">#}
<div class="panel top-articles">
    <div class="panel-heading">
        <h2><a href="{% url 'articles:list' %}">Все статьи о ЗОЖ</a></h2>
    </div>

    <div class="panel-body news-block-list--narrow">
    {% for object in object_list %}
      {% if forloop.counter == 4 %}
      <div class="grid__col-12">
{#          {% show_banner_place 'TourBusinessBlock_1_2' %}#}
        </div>
      {% endif %}
      {% include "news/blocks/_article_top_item.html" %}
    {% endfor %}
    </div>

    <div class="panel-footer">
        <p class="align-center">
            <a href="{% url 'articles:list' %}" class="btn2">Все статьи по ЗОЖ</a>
        </p>
    </div>
</div>
{% endif %}

news/templates/news/blocks/news_photo_wrap.html
{% load thumbnail %}
<div class="photo-wrap">
  <a href="{{ object.get_absolute_url }}">
    {% thumbnail object.get_cover.image "320x200" crop="center" as img %}
    <img src="{{ img.url }}" alt="">
    {% empty %}
    <img class="noimage" src="/static/images/noimage300x180.png" alt="новость без фото">
    {% endthumbnail %}
  </a>
  <span class="photo__title photo__title--right">
    <span title="количество просмотров" class="visits_count noselect">
      <span class="fa fa-eye"></span> {{ object.get_visits }}
    </span>
    {% if object.video %}
    <a class="news-block__has-video" href="{{ object.video.get_absolute_url }}">
        <span class="fa fa-video-camera"></span>
    </a>
    {% endif %}

    {% if object.youtube_video %}
    <a class="news-block__has-video" href="{{ object.get_absolute_url }}">
        <span class="fa fa-video-camera"></span>
    </a>
    {% endif %}

    {% if object.is_photogallery %}
    <a class="news-block__has-photogallery" href="{{ object.photogallery.get_absolute_url }}">
        <span class="fa fa-camera"></span>
    </a>
    {% endif %}
  </span>
</div>

news/templates/news/blocks/news_slider_item.html
<section class="news-block">{% load thumbnail %}
    <div class="photo-wrap">
      {% thumbnail object.get_cover "480x300" crop="center" as image %}
        <span class="photo__img" style="background-image: url({{ image.url }})">
        </span>
        {% endthumbnail %}
        <div class="photo__title">
            <h2><a href="{{ object.get_absolute_url }}">
                {{ object.title }}
            </a></h2>
        </div>
    </div>

    <div class="news-block__text">
        <a href="{{ object.get_absolute_url }}" class="link-more">
            {{ object.text|striptags|truncatewords:"30"|safe }}
        </a>
    </div>

    <div class="news-block__footer">
        {% ifnotequal object.countries.count 0 %}
        {% with object.countries.all as labels %}
            {% include "includies/blocks/labels.html" %}
        {% endwith %}
        {% endifnotequal %}

        <div class="no-labels">
            <span class="news-block__date date">
                <span class="fa fa-clock-o"></span> {{ object.pubdate|date:"d M y"}}
            </span>

            {% ifnotequal object.get_comment_count 0 %}
            <a class="news-block__comments" href="{{ object.get_absolute_url }}#comments">
                <span class="fa fa-comment"></span> {{ object.get_comment_count }}
            </a>
            {% endifnotequal %}

            {% if object.video %}
            <a class="news-block__has-video" href="{{ object.video.get_absolute_url }}">
                <span class="fa fa-video-camera"></span>
            </a>
            {% endif %}

            {% if object.photogallery %}
            <a class="news-block__has-photogallery" href="{{ object.photogallery.get_absolute_url }}">
                <span class="fa fa-camera"></span>
            </a>
            {% endif %}
        </div>
    </div>
</section>

news/templates/news/blocks/top_news.html
<div class="panel top-news">
  <div class="panel-heading">
    <h1><a href="{% url 'news:list' %}">Новости ЗОЖ</a></h1>
  </div>

  <div class="panel-body news-block-list--narrow">
    {% for object in object_list %}
      {% include "news/blocks/_news_item.html" %}
    {% endfor %}
  </div>
  <div class="panel-footer">
    <p class="align-center">
      <a href="{% url 'news:list' %}" class="btn2">Все новости ЗОЖ</a>
    </p>
  </div>
</div>

news/templates/news/blocks/top_news_subject.html
<div class="panel top-news">
  <div class="panel-heading">
    <h2><a href="{% url 'news-list' %}">{{ subject }}</a></h2>
  </div>

  <div class="panel-body news-block-list--narrow">
    {% for object in object_list %}
      {% load thumbnail %}
      <section class="news-block">
        <div class="news-block__header">
          {% block header %}{# ЭТАЛОН ХЕДЕРА #}
            <div class="photo-wrap">
              <a href="{{ object.get_absolute_url }}">
                {% thumbnail object.get_cover.image "480x360" crop="center" as image %}
                  <img  src="{{ image.url }}" alt="" style="height: 280px">
                {% empty %}
                  {% thumbnail NOIMAGE_URL "480x360" crop="center" as noimage %}
                    <img src="{{ noimage.url }}" class="noimage" alt="">
                  {% endthumbnail %}
                {% endthumbnail %}</a>

              <span class="photo__title photo__title--right">
                {% ifnotequal object.get_comment_count 0 %}
                  <a class="counter-icon news-block__comments" href="{{ object.get_absolute_url }}#comments"
                     title="Количество комментариев">
                    <span class="fa fa-comment"></span> {{ object.get_comment_count }}
                </a>
                {% endifnotequal %}

                {% if object.video or object.youtube_video %}
                  <a class="counter-icon news-block__has-video" href="{{ object.video.get_absolute_url }}"
                     title="Видео">
                    <span class="fa fa-video-camera"></span>
                </a>
                {% endif %}

                {% if object.photogallery %}
                  <a class="counter-icon news-block__has-photogallery" href="{{ object.photogallery.get_absolute_url }}"
                     title="Фотографии">
                    <span class="fa fa-camera"></span>
                </a>
                {% endif %}

                <span title="Количество просмотров" class="counter-icon visits_count noselect">
                    <span class="fa fa-eye"></span> {{ object.get_visits }}
                </span>
            </span>
            </div>
          {% endblock %}
        </div>

        <div class="news-block__body">
          {% block body %}
            <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>

            <div class="news-block__text">
              <a class="link-more" href="{{ object.get_absolute_url }}">
                {{ object.text|striptags|truncatewords:"35"|safe }}
              </a>
            </div>
          {% endblock %}
        </div>

        <div class="news-block__footer">
          {% block footer %}
            {% ifnotequal object.countries.count 0 %}
              {% with object.countries.all as labels %}
                {% include "redesign2/blocks/labels.html" %}
              {% endwith %}
            {% endifnotequal %}

            <div class="no-labels">
            <span class="news-block__date date">
                <span class="fa fa-clock-o"></span> {{ object.pubdate|date:"d M y" }}
            </span>
            </div>
          {% endblock %}
        </div>
      </section>

    {% endfor %}
  </div>

  <div class="panel-footer panel-footer--center">

    {% if request.user.is_authenticated %}
      {% if request.user.is_advertiser %}
        <a href="/profi/emails/" class="btn btn-small btn-default">
          Подписаться
        </a>
      {% elif request.user.is_custom_user %}
        <a href="{% url 'accounts_subscriptions' %}" class="btn btn-small btn-default">
          Подписаться
        </a>
      {% endif %}
    {% else %}
      <span class="btn btn-small btn-default open-popup" data-target="#login-popup" title="Требуется авторизация">
            Подписаться
        </span>
    {% endif %}

    <a href="{% url 'news-list' %}" class="btn2">Все новости туризма</a>
  </div>
</div>

news/templates/news/blocks/top_specialblock_slider.html
{% extends "includies/blocks/slider.html" %}

{% block slider_title %}{{ specialblock_title }}{% endblock %}

{% block slider_body %}
    {% for object in object_list %}
        <li class="news-slider__element">
        {% include "news/blocks/news_slider_item.html" %}
        </li>
    {% endfor %}
{% endblock %}

news/templates/news/blocks/top_specialblocks.html
{% for object in object_list %}
  {% with object.name as specialblock_title %}
    {% with object.get_latest_news as object_list %}
      {% include "news/blocks/top_specialblock_slider.html" %}
    {% endwith %}
  {% endwith %}
{% endfor %}

news/templates/news/blocks/top_topic_day_news.html
{% load thumbnail cache %}
  <div class="panel-heading" style="padding-bottom: 0">
    <h3>ТЕМЫ ДНЯ:</h3>
  </div>
  <div class="panel-body">
    <div id="{{ topics_carousel }}" class="owl-carousel">
      {% for topic in topics %}
        <div class="hovereffect item-yandex-carusel">
          <a class="unit" href="{{ topic.get_absolute_url }}">
            <div class="item-owl-carousel">
              {% thumbnail topic.image "165x134" crop='center' as im %}
                <img src="{{ im.url }}" width="100%" height="{{ im.height }}" class="p-5">
              {% endthumbnail %}
              <div class="topic-overlay">
                {{ topic.title|truncatechars:35 }}
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div><!-- /.panel-body -->