news/article/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    ArticleDetailView,
    RubricArticleListView,
)

app_name = 'articles'

urlpatterns = [
    # '',
    url(r'^$', ArticleListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), name="detail"),
    url(r'^(?P<rubric_name>.*)/$', RubricArticleListView.as_view(), name='article_by_rubric'),
]

news/urls.py
from django.urls import path, re_path

from .views import NewsList, NewsRubric, NewsDetail, NewsStories, CountryNewsListView

app_name = 'news'

urlpatterns = [
    path('', NewsList.as_view(), name='list'),
    re_path(r'^news-(?P<slug>.*)/$', CountryNewsListView.as_view(),name='news-by-country'),
    path('<int:pk>/', NewsDetail.as_view(), name='detail'),
    path('<slug:slug>/', NewsRubric.as_view(), name='rubric'),
    path('stories/<slug:slug>/', NewsStories.as_view(), name='stories'),
]

pomogator/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.static import serve

from core.views import SearchResultsView, FeedbackView
from filebrowser.sites import site as filebrowser_site
from news.views import IndexPage
from pomogator import settings
from pomogator.feeds import show_feed
from pomogator.sitemap import StaticSitemap, DinamicNewsSitemap, DinamicArticleSitemap, DinamicPageSitemap, \
    DinamicRubricSitemap, DinamicCountrySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticSitemap,
    'rubrics': DinamicRubricSitemap,
    'news': DinamicNewsSitemap,
    'article': DinamicArticleSitemap,
    'page': DinamicPageSitemap,
    'country': DinamicCountrySitemap,
}

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', filebrowser_site.urls),
    path('trumbowyg/', include('trumbowyg.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('news/', include('news.urls', namespace='news')),
    path('articles/', include('news.article.urls', namespace="articles")),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    # partners
    re_path(r'^', include('partners.urls')),
    #
    re_path(r'^robots\.txt', include('robots.urls')),
    # re_path(r'^sitemap.xml$', cache_page(60)(sitemap), {'sitemaps': [sitemaps]}, name='cached-sitemap'),
    re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='cached-sitemap'),
    re_path(r'^feed/(?P<feed_name>.*)\.xml$', show_feed),
    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    re_path(r'^(?P<url>.*/)$', views.flatpage),

]

news/article/views.py
import logging

# from django.http import Http404
from django.core.cache import cache
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView

from core.mixins import VisitViewMixin
from ..models import Article, Rubric
from countries.models import Country

log = logging.getLogger(__name__)


class ArticleListView(ListView):
    paginate_by = 20
    template_name = "articles/article_list.html"
    model = Article
    current_country = None
    current_tourismtype = None

    def get(self, request, *args, **kwargs):
        return super(ArticleListView, self).get(request, *args, **kwargs)

    def get_queryset(self, **kwargs):
        # print(self.request.GET.get('tourismtype'))

        qs = self.model.objects.filter(
            published=True, pubdate__lte=timezone.now())

        if 'country' in self.request.GET:
            country_slug = self.request.GET.get('country')
            self.current_country = get_object_or_404(
                Country, slug=country_slug)
            qs = qs.filter(countries=self.current_country)

        return qs

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['h1'] = "Журнал: статьи по туризму"
        context['show_map'] = True
        context['current_country'] = self.current_country
        context['current_tourismtype'] = self.current_tourismtype
        return context


class ArticleDetailView(VisitViewMixin, DetailView):
    template_name = "articles/article_detail.html"
    model = Article
    queryset = Article.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        same_articles = Article.objects.filter(
            published=True
        ).exclude(id=self.object.id).order_by("-created")

        if same_articles.count():
            context['same_articles'] = same_articles[0]

        return context


class RubricArticleListView(ListView):
    paginate_by = 20
    model = Article
    template_name = "articles/article_list.html"
    rubric = None
    current_country = None
    current_tourismtype = None

    def get(self, request, *args, **kwargs):
        self.rubric = get_object_or_404(Rubric, title_en=kwargs['rubric_name'])
        return super(RubricArticleListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(published=True, rubrics=self.rubric)

    def get_context_data(self, **kwargs):
        context = super(RubricArticleListView, self).get_context_data(**kwargs)
        context['h1'] = self.rubric.title
        context['show_map'] = False
        context['current_country'] = self.current_country
        context['rubric'] = self.rubric
        return context

news/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404
# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from core.mixins import VisitViewMixin
from countries.models import Country
from news.models import News, Rubric, Stories


class IndexPage(TemplateView):
    template_name = 'index.html'


class NewsList(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list.html'

    def get_queryset(self):
        qs = self.model.objects.filter(published=True)
        return qs


class NewsRubric(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list.html'
    rubric = None

    def get_queryset(self):
        rubric = get_object_or_404(Rubric, slug=self.kwargs.get('slug', None))
        # rubric = Rubric.objects.get(slug=self.kwargs.get('slug', None))
        self.rubric = rubric
        qs = self.model.objects.filter(published=True)
        qs = qs.filter(rubrics=rubric)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewsRubric, self).get_context_data(**kwargs)
        context['rubric'] = self.rubric
        return context


class NewsStories(ListView):
    model = News
    paginate_by = 20
    template_name = 'news/list_stories.html'
    rubric = None

    def get_queryset(self):
        rubric = get_object_or_404(Stories, slug=self.kwargs.get('slug', None))
        # rubric = Rubric.objects.get(slug=self.kwargs.get('slug', None))
        self.rubric = rubric
        qs = self.model.objects.filter(published=True)
        qs = qs.filter(stories=rubric)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewsStories, self).get_context_data(**kwargs)
        context['rubric'] = self.rubric
        return context


class NewsDetail(VisitViewMixin, DetailView):
    model = News
    template_name = 'news/detail.html'
    queryset = News.objects.all_objects().filter(Q(published=True) | Q(delayed_publication=True))


class CountryNewsListView(ListView):
    paginate_by = 20
    template_name = "news/list_country.html"

    def get_queryset(self, **kwargs):
        return News.objects.filter(
            published=True,
            countries__slug=self.kwargs.get('slug')
        )

    def get_context_data(self, **kwargs):
        context = super(CountryNewsListView, self).get_context_data(**kwargs)
        context['country'] = get_object_or_404(
            Country,
            slug=self.kwargs.get('slug')
        )
        return context

news/templates/news/base.html
{% extends 'base.html' %}{% load banner_tags %}
{% block seo_meta %}
  <link rel="canonical" href="{% block canonical_url %}{% endblock %}">{% endblock %}
{% block breadcrumbs %}
  <a href="{% url 'news:list' %}">Новости ЗОЖ</a>
{% endblock %}
{% block main %}
  <div class="grid grid--bleed" id="{% block main_block_css_id %}news-page{% endblock %}">
    <div class="grid__col-sm-9 left-col" style="padding-top: 10px">
      <div class="panel">
        <div class="panel-heading">
          {% block heading %}
            <h1>Новости Здорового Образа Жизни | от ЗОЖ.news </h1>
            {% if show_return_link %}
              <a href="{% url 'news-list' %}" class="pull-right return-link">Вернуться ко всем новостям</a>
            {% endif %}
          {% endblock %}
        </div>
        {% block heading-description %}
          <div class="panel-body" style="padding-bottom: 20px">
            <div class="block description">
              Лента новостей о ЗОЖ - источник оперативной и достоверной информации в мире Здорового Образа Жизни.
              Новости нашего издательского дома широко цитируемы в рунете, однако мы не ограничиваемся лишь темой
              Здорового и правильного питания: на нашей ленте новостей о Здоровом Образе Жизни вы найдёте исследования в
              области правильного похудения, физической активности, а также вредных и полезных привычек для ЗОЖ.
            </div>

          </div>
        {% endblock %}
        {% block page_content %}{% endblock %}
      </div>

      </div>
    <div class="grid__col-sm-3 right-col">
      {% get_widget_scripts section=4 %}
    </div>
  </div>
{% endblock %}

{% block extra_popups %}{% endblock %}

news/templates/news/detail.html
{% extends 'news/base.html' %}{% load thumbnail banner_tags news %}

{% block seo_title %}{{ object.title }} | Новости ЗОЖ{% endblock %}
{% block seo_description %}{{ object.text|striptags|truncatechars:150 }}{% endblock %}
{% block seo_keywords %}{{ object.title }}{% endblock %}
{% block canonical_url %}{{ request.build_absolute_uri }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <span>{{ object.title }}</span>
{% endblock %}
{% block heading %}
  <h1>{{ object.title }}</h1>
  <div class="subheading block">
    <em><a href="{% url 'news:list' %}"
           title="Все новости"
           class="link-subtitle">Все новости </a> /
      <a href="{% url 'news:rubric' object.rubrics.all.0.slug %}" title="{{ object.rubrics.all.0.title }}"
         class="link-subtitle">{{ object.rubrics.all.0.title }}</a></em><br>
  </div>
  <div class="block">
    {% ifnotequal object.countries.count 0 %}
      {% with object.countries.all as labels %}
        {% include "includies/blocks/labels.html" %}
      {% endwith %}
    {% endifnotequal %}

    <span class="news-block__date date" style="padding-left: 10px;">
            <span class="fa fa-clock-o"></span> {{ object.pubdate|date:"d M y" }}
            <span title="количество просмотров" class="visits_count noselect">
                <span class="fa fa-eye"></span> {{ object.get_visits }}
            </span>
        </span>

    {% ifnotequal object.get_comment_count 0 %}
      <a class="news-block__comments" href="{{ object.get_absolute_url }}#comments">
        <span class="fa fa-comment"></span> {{ object.get_comment_count }}
      </a>
    {% endifnotequal %}

    {% if object.video %}
      <a class="news-block__has-video" href="{{ object.video.get_absolute_url }}">
        <span class="fa fa-video-camera"></span>
      </a>
    {% endif %}

    {% if object.photogallery %}
      <a class="news-block__has-photogallery" href="{{ object.photogallery.get_absolute_url }}">
        <span class="fa fa-camera"></span>
      </a>
    {% endif %}
  </div>
{% endblock %}
{% block heading-description %}{% endblock %}
{% block page_content %}
  <div class="">
    {% if object.youtube_video %}
      <div class="video-frame-wrap">
        <iframe
                allowfullscreen=""
                frameborder="0"
                height="360"
                 width="100%"
                src="{{ object.get_youtube_embed }}"></iframe>
      </div>
      {% else %}{# paste cover #}
      {% if object.get_normal_photos|length > 1 %}
        <div class="unslider--bottom-controls">
          <div class="slider" data-autoplay="false">
            <ul>
              {% for newsphoto in object.get_normal_photos %}
                {% thumbnail newsphoto.image "960x640" crop="center" as img %}
                  <li class="photo-wrap">
                    <div class="photo">
                      <img src="{{ img.url }}" alt="{{ newsphoto.description|default:"" }}">
                      {% if newsphoto.description %}
                        <div class="photo__title">{{ newsphoto.description }}</div>{% endif %}
                    </div>
                  </li>
                {% endthumbnail %}
              {% endfor %}
            </ul>
          </div>
        </div>
      {% else %}
        <div class="photo-wrap">
          <img class="photo__img" src="{{ object.get_cover.image.url }}"
               alt="{{ object.get_cover.description|default:object.title|safe }}">
          <div data-relap-id="ZZplzA3NQ6Ren7-_" class="js-relap-anchor"></div>

          <div class="photo__title">
            {{ object.get_cover.description|default:object.title|safe }}
          </div>

        </div>
      {% endif %}
    {% endif %}
    {% include 'includies/blocks/_subscribers_news.html' %}
    <div class="p-b-10 p-t-10">{% get_widget_scripts section=2 %}</div>
    <div class="block panel-body-wrap--padding news-detail hentry" style="margin-top: 0">
      <article class="hentry">
        {{ object.text|safe }}
      </article>
      {% top_topics_day_news news_block=False %}
      <div class="p-t-10">{% get_widget_scripts section=3 %}</div>
    </div>

  </div>
{% endblock %}

news/templates/news/list.html
{% extends 'base.html' %}{% load custom_utils banner_tags news %}
{% block seo_title %}{% if rubric %}{{ rubric.title }} |{% endif %} Новости ЗОЖ - газета о Здоровом Образе Жизни
  {% if page_obj.number != 1 %} Страница {{ page_obj.number }}{% endif %}{% endblock %}
{% block seo_keywords %}{% if rubric %}{{ rubric.title }} {% endif %}новости ЗОЖ, Здоровый образ жизни, Здоровое и
  правильное питание, Правильное похудение,
  Правильная физическая активность{% endblock %}
{% block seo_description %}{% if rubric %}{{ rubric.text|striptags }}{% else %}Новости Здорового Образа Жизни - газета
  ЗОЖ | от ЗОЖ.news{% endif %} {% if page_obj.number != 1 %} Страница {{ page_obj.number }}{% endif %}{% endblock %}
{% block breadcrumbs %}
  <a href="{% url 'news:list' %}">Новости ЗОЖ</a>
  {% if rubric %}<a herf="">{{ rubric }}</a>{% endif %}
{% endblock %}
{% block main %}
  <div class="grid grid--bleed" id="news-page">
    <div class="grid__col-sm-9 left-col" style="padding-top: 10px">
      <div class="news-list block">
        <div class="panel top-main-news">
          {% top_topics_day_news news_block=False %}
        </div>
      </div>
      <div class="panel">
        <div class="panel-heading">
          {% if rubric %}
            <h1>{{ rubric.title }} | Новости ЗОЖ</h1>
          {% else %}
            <h1>Новости Здорового Образа Жизни - газета ЗОЖ | от ЗОЖ.news</h1>
          {% endif %}
        </div>
        {% block heading-description %}
          <div class="panel-body" style="padding-bottom: 20px">
            <div class="block description">
              {% if rubric.description %}
                {{ rubric.description }}
              {% else %}
                Лента новостей о ЗОЖ - источник оперативной и достоверной информации в мире Здорового Образа Жизни.
                Новости нашей газеты ЗОЖ широко цитируемы в рунете, однако мы не ограничиваемся лишь темой Здорового и
                правильного питания: на нашей ленте новостей о Здоровом Образе Жизни вы найдёте исследования в области
                правильного похудения, физической активности, а также вредных и полезных привычек для ЗОЖ.
              {% endif %}
            </div>

          </div>
        {% endblock %}
      </div>
      {% block page_content %}
        {% include 'news/news_list_items.html' %}
        {% include 'includies/paginator2.html' %}
      {% endblock %}
    </div>
    <div class="grid__col-sm-3 right-col">
      {% get_widget_scripts section=4 %}
    </div>
  </div>
{% endblock %}

news/templates/news/list_country.html
{% extends 'base.html' %}{% load custom_utils banner_tags news %}
{% block seo_title %}Новости ЗОЖ {{ country.title_rod }}{% endblock %}
{% block seo_keywords %}новости ЗОЖ в {{ country.title_rod }}, Здоровый образ жизни {{ country.title_rod }}, Здоровое и
  правильное питание, Правильное похудение {{ country.title_rod }}, Правильная физическая активность
  {{ country.title_rod }}{% endblock %}
{% block seo_description %}Новости ЗОЖ {{ country.title_rod }} - всё о Здоровом образе жизни в {{ country.title_rod }}
  - профессионально и оперативно{% endblock %}
{% block breadcrumbs %}
  <a href="{% url 'news:list' %}">Новости ЗОЖ {{ country.title_rod }} </a>
  {% if rubric %}<a herf="">{{ rubric }}</a>{% endif %}
{% endblock %}
{% block main %}
  <div class="grid grid--bleed" id="news-page">
    <div class="grid__col-sm-9 left-col" style="padding-top: 10px">
      <div class="panel">
        <div class="panel-heading">
          <h1>Новости ЗОЖ {{ country.title_rod }} </h1>
        </div>
        {% block heading-description %}
          <div class="panel-body" style="padding-bottom: 20px">
            <div class="block cover">
              {% block cover %}
                <div class="block map">
                  <img width="100%" src="{{ rubric.image.url }}" alt="{{ subject.name }}" title="{{ subject.name }}"/>
                </div>
              {% endblock %}
              <div class="block description">
                Лента новостей о ЗОЖ в {{ country.title_rod }} - источник оперативной и достоверной информации в мире
                Здорового Образа Жизни.
                Новости нашего издательского дома широко цитируемы в рунете, однако мы не ограничиваемся лишь темой
                Здорового и правильного питания в {{ country.title_rod }}: на нашей ленте новостей о Здоровом Образе
                Жизни
                вы найдёте исследования в {{ country.title_rod }} в
                области правильного похудения, физической активности, а также вредных и полезных привычек для ЗОЖ.
              </div>
            </div>
          </div>
        {% endblock %}
      </div>
      {% block page_content %}
        {% include 'news/news_list_items.html' %}
        {% include 'includies/paginator2.html' %}
      {% endblock %}
    </div>
    <div class="grid__col-sm-3 right-col">
      {% get_widget_scripts section=4 %}
    </div>
  </div>
{% endblock %}

news/templates/news/list_stories.html
{% extends 'base.html' %}{% load custom_utils banner_tags news %}
{% block seo_title %}{% if rubric %}{{ rubric.title }} | {% endif %}Новости ЗОЖ{% endblock %}
{% block seo_keywords %}{% if rubric %}{{ rubric.title }} {% endif %}новости ЗОЖ, Здоровый образ жизни, Здоровое и
  правильное питание, Правильное похудение,
  Правильная физическая активность{% endblock %}
{% block seo_description %}{% if rubric %}{{ rubric.text|striptags }}{% else %}Новости ЗОЖ - всё о Здоровом образе жизни
  - профессионально и оперативно{% endif %}{% endblock %}
{% block breadcrumbs %}
  <a href="{% url 'news:list' %}">Новости ЗОЖ</a>
  {% if rubric %}<a herf="">{{ rubric }}</a>{% endif %}
{% endblock %}
{% block main %}
  <div class="grid grid--bleed" id="news-page">
  <div class="grid__col-sm-9 left-col" style="padding-top: 10px">
    <div class="panel">
      <div class="panel-heading">
        {% if rubric %}
          <h1>{{ rubric.title }} | Новости ЗОЖ</h1>
        {% else %}
          <h1>Новости Здорового Образа Жизни | от ЗОЖ.news</h1>
        {% endif %}
      </div>
      {% block heading-description %}
        <div class="panel-body" style="padding-bottom: 20px">
        <div class="block cover">
          {% block cover %}
            <div class="block map">
              <img width="100%" src="{{ rubric.image.url }}" alt="{{ subject.name }}" title="{{ subject.name }}"/>
            </div>
          {% endblock %}
          <div class="block description">
            {% if rubric.description %}
              {{ rubric.description }}
            {% endif %}
          </div>
        </div>
      {% endblock %}
      </div>
    </div>
    {% block page_content %}
      {% include 'news/news_list_items.html' %}
      {% include 'includies/paginator2.html' %}
    {% endblock %}
  </div>
  <div class="grid__col-sm-3 right-col">
    {% get_widget_scripts section=4 %}
  </div>

{% endblock %}

news/templates/news/news_list_item.html
{% load thumbnail %}{% load custom_utils %}
<section class="news-list__item">
  {% if show_date_circle %}
    <div class="news-item__date hidden-xs hidden-xxs">
      <div class="date-circle">
        <div class="date">{{ object.pubdate|date:"d.m" }}</div>
        <div class="time">{{ object.pubdate|date:"H:i" }}</div>
      </div>
    </div>
  {% endif %}

  <div class="news-item__block news-block">
    <div class="grid">
      <div class="grid__col-sm-6 news-item__header">
        {% block header %}
          {% include "news/blocks/news_photo_wrap.html" %}
        {% endblock %}
      </div>

      <div class="grid__col-sm-6 news-item__body">
        {% block body %}
          <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
          <div class="news-item__text">
            <a class="news-block__text link-more" href="{{ object.get_absolute_url }}">
              {{ object.text|striptags|truncatechars:"480"|balance_title_n_text2:object.title|safe }}
            </a>
          </div>
        {% endblock %}
      </div>
    </div>

    <div class="news-item__footer">
      {% ifnotequal object.countries.count 0 %}
        {% with object.countries.all as labels %}
          {% include "includies/blocks/labels.html" %}
        {% endwith %}
      {% endifnotequal %}

      <div class="no-labels">
      <span class="news-block__date date">
        <span class="fa fa-clock-o"></span> {{ object.pubdate|date:"d M y" }}
      </span>
      </div>
    </div>
  </div>
</section>

news/templates/news/news_list_items.html
{% for object in object_list %}
  {% include 'news/blocks/_forloop_ad_video.html' %}
  {% include 'news/blocks/_forloop_yandex_widget.html' %}
  <div class="news-list__item-wrap p-r-5 p-l-5">
    {% include "news/news_list_item.html" with show_date_circle=1 %}
  </div>
{% endfor %}